### ISSUE TITLE
Ask for complete code

### ISSUE THREAD

**Issue by zhangquan97** [zhou745/GauFuse_WSTAL#1]
Thank you for your wonderful work, when will the complete code be released?

**Comment by zhou745** [comment]
Actually, this is already all the code I used during training and testing.  you can follow https://github.com/sujoyp/wtalc-pytorch for data preparation.  Place the features and annotations inside a dataset/Thumos14reduced/ folder.  Also, I provide the ckpt in my exp at the ckpt folder.

**Comment by zhangquan97** [comment]
Thanks for your reply, I will try to reproduce the algorithm again following the instructions in the link

**Comment by zhou745** [comment]
feel free to ask me if you have any problems.
