### ISSUE TITLE
Problem about train on ActivitiNet

### ISSUE THREAD

**Issue by Lcode119** [zhou745/GauFuse_WSTAL#11]
Hello author, I used the model and RSKP in this paper to train on ActivitiNet, without any modification, and the map obtained has always been 0, is there a problem in what link?
![image](https://github.com/zhou745/GauFuse_WSTAL/assets/74463230/a9c98529-6f86-44fb-aaf9-c97179acee13)

**Comment by zhou745** [comment]
Hi, thx for asking. This seems to be a very deep bug. I would suggest you try RSKP only first and see if the results are still all 0. and then add my prediction module.  Also, training on ActivityNet needs early stop, if my memory is correct, the highest value appears around 50-70 epoches?

**Comment by Lcode119** [comment]
> Hi, thx for asking. This seems to be a very deep bug. I would suggest you try RSKP only first and see if the results are still all 0. and then add my prediction module. Also, training on ActivityNet needs early stop, if my memory is correct, the highest value appears around 50-70 epoches?

Thank you for your reply.That's what I trained on RSKP and the code hasn't changed. I'm wondering if I need to change some parameters, or if I need to change the evaluation function?

**Comment by zhou745** [comment]
Did you mean the original RSKP code? I think you need to ask the author for the code for activity-net. I believe RSKP training on THUMOS and Activitynet are not exactly the same. I remember the author has an independent script. Then you add my predictor to his script, the gain will appear.

**Comment by Lcode119** [comment]
Thank you,I will try again.

**Comment by Lcode119** [comment]
作者您好，上次回复之后我又去尝试了一下。我看到您和RSKP的作者都提到了将代码插入到ACM-NET模型上进行训练，但是这两个模型代码结构差距还是很大的，集成起来比较困难。我处理策略如下：我将ACM-NET模型对于ActivityNet数据集验证的方法（test部分）移到了您的代码基础上。 存在以下几个问题：
1.注意到您的代码是基于RSKP的，但是在ActivityNet上训练参数的设置不同,例如您的scale-factor设置为20，但是我实验发现设置为10效果会好一点。请问参数模型的设置以谁为准呢？
![image](https://github.com/zhou745/GauFuse_WSTAL/assets/74463230/5f84271c-ccbd-46f6-b380-aa6c6a806809)
2.我目前跑出来得最好的效果在22%左右，我怀疑是我代码集成问题，我实在是找不到问题所在了（T_T)，希望您能给点建议。
3.我在训练的时候没有加入高斯融合模块，在测试阶段加入了，但是发现结果下降了。由22%->19%。
4.您在上面提到最好的结果将会在epoch50-70时出现，我实验的时候也发现了最好的结果在30-40epoch时出现。是否意味着最优结果不依赖于视频特征传播策略（epoch100开始使用）和伪标签监督策略（epoch150开始使用）。
希望能得到您的答复，不胜感谢！

**Comment by zhou745** [comment]
ActivityNet 视频特性传输我记得不用等到100个epoch开始，当时我也是询问了rskp的作者才知道。他的超参和thumos差异比较大。 我当时调节的策略是先基于rskp调到作者文中的点数，再加上我的模块调试。 一步到位比较困难。

**Comment by Lcode119** [comment]
> ActivityNet 视频特性传输我记得不用等到100个epoch开始，当时我也是询问了rskp的作者才知道。他的超参和thumos差异比较大。 我当时调节的策略是先基于rskp调到作者文中的点数，再加上我的模块调试。 一步到位比较困难。

非常感谢您的回复，我再去调节一下相关参数。但是我在测试阶段加入高斯融合模块平均精度反而会下降，请问可能是什么原因呢？是否高斯融合模块的相关参数也需要调节？

**Comment by zhou745** [comment]
这个就比较奇怪了。 我当时没有遇到过。 可以试试调节temperature

Lcode119 ***@***.***>于2024年6月18日 周二上午11:05写道：

**Comment by Lcode119** [comment]
好的，非常感谢！
