### ISSUE TITLE
A doubt of Gaussian weighted fusion (testing)

### ISSUE THREAD

**Issue by YoungJT-7274** [zhou745/GauFuse_WSTAL#2]
I can't tell the difference between Gaussian weighted fusion and Gaussian weighted fusion (testing) in the paper.
Can you tell me where the Gaussian weighted fusion strategy is adopted as post-processing during testing in your code？
Thanks a lot.

**Comment by zhou745** [comment]
The Gaussian weighted fusion is employed to produce a high-quality action instance which is a tuple (start time, end time, action score).  During Training, this action tuple can not be directly used and needs to be converted back to snippet-wise pseudo-label by Linpro pseudo-label generation.   During testing,  it is adopted after action segment proposals are raised and generates the final result.

**Comment by YoungJT-7274** [comment]
Thanks for your reply.
