### ISSUE TITLE
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (212,) + inhomogeneous part.

### ISSUE THREAD

**Issue by ydwl-lynn** [zhou745/GauFuse_WSTAL#5]
When I run the code "python main.py", it has the follow error:
Start testing!
Testing test data point 100 of 212
Testing test data point 200 of 212
Traceback (most recent call last):
  File "main.py", line 58, in <module>
    main(training_type=training_type)
  File "main.py", line 38, in main
    processor.processing()
  File "/home1/lyyHD/WTAL/GauFuse_WSTAL/method.py", line 116, in processing
    self.val(self.args.load_epoch)
  File "/home1/lyyHD/WTAL/GauFuse_WSTAL/method.py", line 351, in val
    ss_eval(epoch, self.test_data_loader, self.args, self.logger, self.model_module, self.device)
  File "/home1/lyyHD/WTAL/GauFuse_WSTAL/evaluation/eval.py", line 89, in ss_eval
    frm_preds = np.array(frm_preds)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (212,) + inhomogeneous part.

**Comment by zhou745** [comment]
Can you give me more information? for instance your environment, or did you change anything in the config?  Currently, I suspect it's the data you are using.  Did you download from https://emailucr-my.sharepoint.com/personal/sujoy_paul_email_ucr_edu/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Fsujoy%5Fpaul%5Femail%5Fucr%5Fedu%2FDocuments%2Fwtalc%2Dfeatures%2FThumos14reduced%2DI3D%2DJOINTFeatures%2Enpy&parent=%2Fpersonal%2Fsujoy%5Fpaul%5Femail%5Fucr%5Fedu%2FDocuments%2Fwtalc%2Dfeatures

**Comment by ydwl-lynn** [comment]
environment: torch 2.0.1 numpy 1.24.3 scipy 1.10.1. I haven't changed anything in the config. And the above link you gave can't be opened.

**Comment by zhou745** [comment]
![image](https://github.com/zhou745/GauFuse_WSTAL/assets/35469967/27d94846-8e52-4cbb-8b40-c7da7d2e5fbe)

Are you using the red-circled one as your data?

**Comment by ydwl-lynn** [comment]
Yes, I have downloaded the feature data and used it. Just now I found out the cause of the error and have fixed it, the reason was the version number of the numpy package did not correspond. Reinstalling numpy=1.23.5 solved it.

Also, I have a question: only the test code is given so far, when will the author give the training code and the code for the ActivityNet dataset?

**Comment by ydwl-lynn** [comment]
同学，您好，我是西安理工大学的一名博二的学生，研究方向是多模态学习。对您的这篇论文非常感兴趣，请问是否可以添加微信，进一步详细交流。我的微信号是：13572426761.













At 2023-09-06 16:14:22, "zhou745" ***@***.***> wrote:

Are you using the red-circled one as your data?

**Comment by zhou745** [comment]
Good to know that, Just change the config run_type = 0, and you train the code. I have sent you a friend invitation on WeChat.

**Comment by zhou745** [comment]
close for inactive
