### ISSUE TITLE
'epoch' parameter 

### ISSUE THREAD

**Issue by eeehco** [zhou745/GauFuse_WSTAL#8]
Hello author, several epoch parameters appear in the option.py file, such as' pre trained epoch '. Will they all have an impact on the training results?

**Comment by zhou745** [comment]
The parameter "pre trained epoch " comes from the fact that this work is based on RSKP, and they are using a 200 epoch schedule. Thus we maintained their training schedule. I believe the lr and pseudo-label generation need to be adjusted if you change this parameter.
